# Generated by Django 4.2 on 2023-04-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
    ]
